cutoff_date: "2024-12-31T23:59:59"
output_dir: "data/raw"
request_timeout: 30
rate_limit_sleep: 1.0

# 수집 모드: "all" (모든 exploit) 또는 "cve_list" (특정 CVE만)
mode: "cve_list"

# Exploit을 수집할 CVE 목록
cve_list:
  - CVE-2021-44228  # Log4Shell
  - CVE-2014-0160   # Heartbleed
  - CVE-2014-6271   # Shellshock
  - CVE-2022-22965  # Spring4Shell
  - CVE-2017-5638   # Struts2 RCE
