# LLM 설정

# Provider 설정
providers:
  openai:
    models:
      - gpt-4
      - gpt-4-turbo-preview
      - gpt-3.5-turbo
    default_model: gpt-4
    temperature: 0.3
    max_tokens: 500
    
  anthropic:
    models:
      - claude-3-opus-20240229
      - claude-3-sonnet-20240229
      - claude-3-haiku-20240307
    default_model: claude-3-opus-20240229
    temperature: 0.3
    max_tokens: 500

# 프롬프트 설정
prompt:
  system_message: "당신은 소프트웨어 보안 전문가입니다."
  
  # 프롬프트 템플릿 (Jinja2 형식)
  template: |
    당신은 소프트웨어 보안 전문가입니다. 다음 패키지의 잠재적 취약점 발생 가능성을 평가해주세요.
    
    패키지명: {{ package_name }}
    
    ## 과거 취약점 이력 (CVE 공개 전 시점 기준)
    - 총 CVE 수: {{ total_cves }}개
    - Critical 등급 CVE: {{ critical_cves }}개
    - 평균 CVSS 점수: {{ avg_cvss }}
    - 주요 취약점 유형: {{ vulnerability_types }}
    - 취약점 발생 추세: {{ trend }}
    
    ## 생태계 내 위치
    - PageRank (전역 중요도): {{ pagerank }}
    - 하류 영향 범위: {{ downstream_impact }}개 패키지가 직간접적으로 의존
    - 직접 의존 패키지 수: {{ in_degree }}개
    
    ## 코드 레벨 특징
    - 위험 함수 사용: {{ dangerous_functions }}개
    - 코드 복잡도: {{ complexity }}
    
    {% if cluster_info %}
    ## 유사 패키지 군집 정보
    - 동일 군집 내 유사 패키지: {{ similar_packages }}
    - 공통 패턴: {{ common_patterns }}
    {% endif %}
    
    ## 질문
    위 정보를 바탕으로, 이 패키지에서 향후 Critical 또는 High 등급의 취약점이 발생할 가능성을 평가해주세요.
    
    **중요**: CVE가 공개되기 전 시점이므로, 실제 취약점 정보는 알 수 없습니다. 
    오직 관찰 가능한 사전 신호(과거 이력, 코드 패턴, 생태계 위치)만을 근거로 판단해주세요.
    
    다음 형식으로 답변해주세요:
    1. 위험 점수: 0.0 ~ 1.0 사이의 숫자 (1.0이 가장 위험)
    2. 근거: 왜 이런 점수를 부여했는지 구체적으로 설명
    
    답변 형식:
    RISK_SCORE: [0.0-1.0 사이의 숫자]
    REASONING: [구체적인 근거]

# 배치 처리 설정
batch:
  size: 10              # 동시 처리할 패키지 수
  delay_seconds: 1      # 배치 간 대기 시간 (rate limiting)
  retry_attempts: 3     # 실패 시 재시도 횟수
  retry_delay: 5        # 재시도 대기 시간 (초)

# 비용 최적화
cost_optimization:
  use_cache: true                    # 유사한 프롬프트 캐싱
  cache_similarity_threshold: 0.95   # 캐시 사용 유사도 임계값
  max_packages_per_run: 1000         # 1회 실행당 최대 패키지 수
  prioritize_critical_nodes: true    # 핵심 노드 우선 처리
