# 신호 가중치 설정
# 각 신호 유형의 중요도를 조정

# 최종 점수 계산 시 가중치
final_score_weights:
  signal_score: 0.6  # 신호 기반 점수
  llm_score: 0.4     # LLM 예측 점수

# 신호 기반 점수 내부 가중치
signal_score_weights:
  vulnerability_patterns: 0.4  # 과거 취약점 이력 (가장 중요)
  graph_signals: 0.3           # 그래프 중심성 및 영향력
  code_signals: 0.2            # 코드 레벨 위험 신호
  activity_signals: 0.1        # 유지보수 활동 패턴

# 취약점 패턴 점수 내부 가중치
vulnerability_pattern_weights:
  cve_frequency: 0.3      # CVE 발생 빈도
  critical_ratio: 0.3     # Critical CVE 비율
  avg_cvss: 0.3           # 평균 CVSS 점수
  trend: 0.1              # 추세 (증가/감소)

# 그래프 신호 내부 가중치
graph_signal_weights:
  pagerank: 0.5           # 전역 중요도
  downstream_impact: 0.5  # 하류 영향 범위

# 코드 신호 내부 가중치
code_signal_weights:
  dangerous_functions: 0.6  # 위험 함수 사용
  complexity: 0.4           # 코드 복잡도

# 활동 신호 내부 가중치
activity_signal_weights:
  commit_frequency: 0.5     # 커밋 빈도 (낮으면 위험)
  issue_resolution: 0.5     # 이슈 해결 속도 (느리면 위험)

# 정규화 기준값
normalization_thresholds:
  pagerank_max: 0.001           # PageRank 0.001 이상이면 매우 높음
  downstream_impact_max: 10000  # 10000개 이상 의존하면 매우 높음
  dangerous_functions_max: 50   # 50개 이상이면 매우 위험
  complexity_max: 100           # 복잡도 100 이상이면 매우 복잡
  cve_frequency_max: 5.0        # 연간 5개 이상이면 매우 높음
  commit_frequency_max: 100     # 3개월간 100개 이상이면 활발

# 위험 등급 임계값
risk_thresholds:
  critical: 0.8   # 0.8 이상: Critical
  high: 0.6       # 0.6-0.8: High
  medium: 0.4     # 0.4-0.6: Medium
  low: 0.0        # 0.4 미만: Low
